# Generated by Django 5.1.4 on 2025-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_findroompost_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalpost',
            name='max_occupants',
            field=models.IntegerField(null=True),
        ),
    ]
