# Generated by Django 5.1.4 on 2025-01-22 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='image_url',
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app.image'),
        ),
    ]
