# Generated by Django 5.1.4 on 2025-01-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='app.rentalpost'),
        ),
    ]
